program = { statement }

statement = declare-statement | expression-statement | if-statement | while-statement | function-statement | return-statement

function-statement = "func" identifier [ parameter-list ] "{" { statement } "}"

parameter-list = ":" identifier { "," identifier }

return-statement = "return" [ expression ]

declare-statement = "let" identifier ":=" expression

expression-statement = expression [ "=" expression ]

if-statement = "if" expression "{" { statement } "}" { else-if-statement } [ else-statement ]

else-if-statement = "else" "if" expression "{" { statement } "}"

else-statement = "else" "{" { statement } "}"

while-statement = "while" expression "{" { statement } "}"

expression = expression-term { "||" expression-term }

expression-term = expression-unary { "&&" expression-unary }

expression-unary = "!" expression-unary | comparison

comparison = arithmetic [ ("==" | "!=" | ">" | ">=" | "<" | "<=") arithmetic ]

arithmetic = arithmetic-term { ("+" | "-") arithmetic-term }

arithmetic-term = arithmetic-unary { ("*" | "/") arithmetic-unary }

arithmetic-unary = "-" arithmetic-unary | factor

factor = primary { "[" arithmetic "]" }

primary = number | identifier | "(" expression ")" | string | array-literal | "true" | "false" | function-call | function-literal | "void"

function-literal = "func" [ parameter-list ] "{" { statement } "}"

function-call = identifier "(" [ expression-list ] ")"

array-literal = "[" [ expression-list ] "]"

expression-list = expression { "," expression }